# tasks file for pycharm
---
- name: create (download) directory
  file:
   path: "{{ pycharm_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - pycharm
    - pycharm-downloads

- name: download
  get_url:
    url: "{{ Webserver_Location }} {{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - pycharm
    - pycharm-downloads

- name: install
  unarchive:
    src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar"
    dest: "{{ pycharm_install_prefix }}"
    creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_version }}"
    remote_src: false
  tags:
    - configuration
    - pycharm
    - pycharm-install

- name: Create Symbolic Link for pycharm
  file:
    src: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version}}/{{ pycharm_execution_file }}"
    dest: "/usr/bin/pycharm"
    state: link
  tags:
    - configuration
    - pycharm
    - pycharm-install

- name: Remove Pycharm .tar and install directory
  file:
    state: absent
    path: "{{ pycharm_downloads_path }}"
  tags:
    - configuration
    - clean-up
    - pycharm
